# This file maintains maxwell's preferred ruby style 2022-0208

#
# Ignore cookstyle complaints about the use of normal attributes
# I specifically use normal attributes with firewall attributes
# in order to save the attribute to the node for persistence
#

Chef/Correctness/NodeNormal:
  Exclude:
    - '**/metadata.rb'
    - '**/Berksfile'
    - 'recipes/deploy.rb'
  Enabled: false

#
# Ignore complaints about extra lines before and after blocks
# I like the extra white space for code visibility
#

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'recipes/deploy.rb'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
  EnforcedStyle: empty_lines
