---
driver:
  name: vagrant
  synced_folders:
    - ['./data', '/kitchen/data']
  network:
  - ["private_network", {ip: "10.0.2.0"}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  cookbooks_path: ../cookbooks
  environments_path: ../../environments
  data_bags_path: ../../data_bags
  roles_path: ../../roles
  nodes_path: test/integration/nodes

verifier:
  name: inspec

platforms:
  - name: centos8

suites:
  - name: deploy
    run_list:
      - recipe[maxlab-dhcp::deploy]
#    verifier:
#      inspec_tests:
#        - test/integration/default
    provisioner:
      client_rb:
        environment: maxlab
