name 'maxlab_smartd'
maintainer 'Maxwell Spangler'
maintainer_email 'maxcode@maxwellspangler.com'
license 'All Rights Reserved'
description 'Deploys smartd daemon to monitor storage S.M.A.R.T. health attributes and alert on issues'
version '1.3.1'
chef_version '>= 14.0'

supports 'redhat', '>= 7.0'
supports 'centos', '>= 7.0'
