name 'maxlab_prometheus'
maintainer 'Maxwell Spangler'
maintainer_email 'maxcode@maxwellspangler.com'
license 'All Rights Reserved'
description 'Deploys Prometheus Server or Node Exporter'
version '1.0.0'
chef_version '>= 14.0'

supports 'redhat', '>= 7.0'
supports 'centos', '>= 7.0'
