name 'maxlab_samba'
maintainer 'Maxwell Spangler'
maintainer_email 'maxcode@maxwellspangler.com'
license 'All Rights Reserved'
description 'Deploys basic Samba CIFS file server services.'
version '1.3.1'
chef_version '>= 14.0'

supports 'redhat', '>= 7.0'
supports 'centos', '>= 7.0'
