---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  cookbooks_path: ../../cookbooks
  data_bags_path: ../../data_bags
  nodes_path: test/integration/nodes

verifier:
  name: inspec

platforms:
  - name: maxlab-centos-chef

suites:
  - name: deploy
    run_list:
    verifier:
      inspec_tests:
        - test/integration/deploy
    attributes:
      kitchen_testing_maxlab: true
      chef-vault:
        # Instruct chef_vault_item to use local raw files when vaulted data is not available.
        databags_fallback: true
    provisioner:
       policyfile: Policyfile.rb
